name: ci/cd

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "17 3 * * *"
  
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: [ '8.5', '8.6', '8.7', '8.8', '8.9' ]
    name: Racket ${{ matrix.racket-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.10
        with:
          architecture: 'x64'
          distribution: 'full'
          version: ${{ matrix.racket-version }}
      - name: Run Tests
        run: raco test main.rkt
